import 'package:fittrack/models/exercises/Exercise.dart';

List<Exercise> exercises = [
  Exercise(name: 'Ab Wheel', category: 'Core'),
  Exercise(name: 'Arnold Press', category: 'Shoulders', equipment: 'Dumbbell'),
  Exercise(name: 'Around The World', category: 'Chest', equipment: 'Dumbbell'),
  Exercise(name: 'Back Extension', category: 'Back'),
  Exercise(name: 'Back Extension', category: 'Back', equipment: 'Machine'),
  Exercise(name: 'Ball Slams', category: 'Full Body'),
  Exercise(name: 'Battle Ropes', category: 'Full Body'),
  Exercise(name: 'Bench Dip', category: 'Triceps'),
  Exercise(name: 'Bench Press', category: 'Chest', equipment: 'Barbell'),
  Exercise(name: 'Bench Press', category: 'Chest', equipment: 'Dumbbell'),
  Exercise(name: 'Bench Press', category: 'Chest', equipment: 'Cable'),
  Exercise(
      name: 'Bench Press - Close Grip',
      category: 'Chest',
      equipment: 'Barbell'),
  Exercise(
      name: 'Bench Press - Wide Grip', category: 'Chest', equipment: 'Barbell'),
  Exercise(name: 'Bent Over Row', category: 'Back', equipment: 'Dumbbell'),
  Exercise(name: 'Bent Over Row', category: 'Back', equipment: 'Dumbell'),
  Exercise(name: 'Bent Over Row', category: 'Back', equipment: 'Band'),
  Exercise(
      name: 'Bent Over Row - Underhand',
      category: 'Back',
      equipment: 'Barbell'),
  Exercise(name: 'Bicep Curl', category: 'Biceps', equipment: 'Machine'),
  Exercise(name: 'Bicep Curl', category: 'Biceps', equipment: 'EZ Bar'),
  Exercise(name: 'Bicep Curl', category: 'Biceps', equipment: 'Dumbbell'),
  Exercise(name: 'Bicep Curl', category: 'Biceps', equipment: 'Barbell'),
  Exercise(name: 'Bicep Curl', category: 'Biceps', equipment: 'Cable'),
  Exercise(name: 'Bicycle Crunch', category: 'Core'),
  Exercise(name: 'Box Jump', category: 'Legs'),
  Exercise(name: 'Box Squat', category: 'Legs', equipment: 'Barbell'),
  Exercise(name: 'Bulgarian Split Squat', category: 'Legs'),
  Exercise(
      name: 'Bulgarian Split Squat', category: 'Legs', equipment: 'Dumbbell'),
  Exercise(name: 'Burpee', category: 'Full Body'),
  Exercise(name: 'Carble Crossover', category: 'Chest', equipment: 'Carble'),
  Exercise(name: 'Cable Crunch', category: 'Core', equipment: 'Cable'),
  Exercise(name: 'Cable Kickback', category: 'Triceps', equipment: 'Cable'),
  Exercise(name: 'Cable Pull Through', category: 'Legs', equipment: 'Cable'),
  Exercise(name: 'Cable Twist', category: 'Core', equipment: 'Cable'),
  Exercise(
      name: 'Calf Press on Leg Press',
      category: 'Calves',
      equipment: 'Machine'),
  Exercise(
      name: 'Calf Press on Seated Leg Press',
      category: 'Calves',
      equipment: 'Machine'),
  Exercise(name: 'Chest Dip', category: 'Chest'),
  Exercise(name: 'Chess Dip (Assisted)', category: 'Chest'),
  Exercise(name: 'Chest Fly', category: 'Chest', equipment: 'Machine'),
  Exercise(name: 'Chest Fly', category: 'Chest', equipment: 'Band'),
  Exercise(name: 'Chest Fly', category: 'Chest', equipment: 'Dumbbell'),
  Exercise(name: 'Chest Fly', category: 'Chest', equipment: 'Cable'),
  Exercise(name: 'Chest Press', category: 'Chest', equipment: 'Machine'),
  Exercise(name: 'Chin Up', category: 'Back'),
  Exercise(name: 'Chin Up (Assisted)', category: 'Back'),
  Exercise(name: 'Clean', category: 'Olympic', equipment: 'Barbell'),
  Exercise(name: 'Clean and Jerk', category: 'Olympic', equipment: 'Barbell'),
  Exercise(
      name: 'Concentration Curl', category: 'Biceps', equipment: 'Dumbbell'),
  Exercise(name: 'Cross Body Crunch', category: 'Core'),
  Exercise(name: 'Crunch', category: 'Core', equipment: 'Machine'),
  Exercise(name: 'Crunch', category: 'Core'),
  Exercise(name: 'Crunch (Stability Ball)', category: 'Core'),
  Exercise(name: 'Cycling', category: 'Cardio'),
  Exercise(name: 'Deadlift', category: 'Back', equipment: 'Band'),
  Exercise(name: 'Deadlift', category: 'Back', equipment: 'Barbell'),
  Exercise(name: 'Deadlift', category: 'Back', equipment: 'Dumbbell'),
  Exercise(
      name: 'Deadlift High Pull', category: 'Olympic', equipment: 'Barbell'),
  Exercise(
      name: 'Decline Bench Press', category: 'Chest', equipment: 'Dumbbell'),
  Exercise(
      name: 'Decline Bench Press', category: 'Chest', equipment: 'Barbell'),
  Exercise(name: 'Decline Crunch', category: 'Core'),
  Exercise(name: 'Deficit Deadlift', category: 'Legs', equipment: 'Barbell'),
  Exercise(name: 'Diamond Push Up', category: 'Triceps'),
  Exercise(name: 'Elliptical Machine', category: 'Cardio'),
  Exercise(name: 'Face Pull', category: 'Back', equipment: 'Cable'),
  Exercise(name: 'Flat Knee Raise', category: 'Core'),
  Exercise(name: 'Flat Leg Raise', category: 'Core'),
  Exercise(name: 'Front Raise', category: 'Shoulders', equipment: 'Dumbbell'),
  Exercise(name: 'Front Raise', category: 'Shoulders', equipment: 'Barbell'),
  Exercise(name: 'Front Raise', category: 'Shoulders', equipment: 'Band'),
  Exercise(name: 'Front Raise', category: 'Shoulders', equipment: 'Cable'),
  Exercise(name: 'Front Raise', category: 'Shoulders', equipment: 'Plate'),
  Exercise(name: 'Front Squat', category: 'Legs', equipment: 'Barbell'),
  Exercise(name: 'Goblet Squat', category: 'Legs', equipment: 'Kettlebell'),
  Exercise(name: 'Good Morning', category: 'Back', equipment: 'Barbell'),
  Exercise(name: 'Hack Squat', category: 'Legs', equipment: 'Machine'),
  Exercise(name: 'Hammer Curl', category: 'Biceps', equipment: 'Band'),
  Exercise(name: 'Hammer Curl', category: 'Biceps', equipment: 'Dumbbell'),
  Exercise(name: 'Hammer Curl', category: 'Biceps', equipment: 'Cable'),
  Exercise(name: 'Handstand Push Up', category: 'Shoulders'),
  Exercise(name: 'Hang Snatch', category: 'Olympic', equipment: 'Barbell'),
  Exercise(name: 'Hanging Knee Raise', category: 'Core'),
  Exercise(name: 'Hanging Leg Raise', category: 'Core'),
  Exercise(name: 'High Knee Skips', category: 'Legs'),
  Exercise(name: 'Hip Abductor', category: 'Legs', equipment: 'Machine'),
  Exercise(name: 'Hip Adductor', category: 'Legs', equipment: 'Machine'),
  Exercise(name: 'Hip Thrust', category: 'Glutes', equipment: 'Barbell'),
  Exercise(name: 'Hip Thrust', category: 'Glutes'),
  Exercise(name: 'Incline Bench Press', category: 'Chest', equipment: 'Cable'),
  Exercise(
      name: 'Incline Bench Press', category: 'Chest', equipment: 'Barbell'),
  Exercise(
      name: 'Incline Bench Press', category: 'Chest', equipment: 'Dumbbell'),
  Exercise(name: 'Incline Chest Fly', category: 'Chest', equipment: 'Dumbbell'),
  Exercise(
      name: 'Incline Chest Press', category: 'Chest', equipment: 'Machine'),
  Exercise(name: 'Incline Curl', category: 'Biceps', equipment: 'Dumbbell'),
  Exercise(name: 'Incline Row', category: 'Back', equipment: 'Dumbbell'),
  Exercise(name: 'Inverted Row', category: 'Back'),
  Exercise(
      name: 'Iso-Lateral Chest Press', category: 'Chest', equipment: 'Machine'),
  // Start at page 6 monogdb (documents 101-120)
];
